Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 13
"GET /about/ HTTP/1.1" 200 8
Watching for file changes with StatReloader
Index page accessed
"GET / HTTP/1.1" 200 13
Error in about page: division by zero
Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp\views.py", line 17, in about
    result = 1 / 0
ZeroDivisionError: division by zero
"GET /about/ HTTP/1.1" 200 27
INFO 2023-08-05 12:23:20,926 autoreload 8120 11452 Watching for file changes with StatReloader
INFO 2023-08-05 12:23:22,801 views 8120 12488 Index page accessed
INFO 2023-08-05 12:23:22,802 basehttp 8120 12488 "GET / HTTP/1.1" 200 13
ERROR 2023-08-05 12:23:26,359 views 8120 12488 Error in about page: division by zero
Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp\views.py", line 17, in about
    result = 1 / 0
ZeroDivisionError: division by zero
INFO 2023-08-05 12:23:26,360 basehttp 8120 12488 "GET /about/ HTTP/1.1" 200 27
INFO 2023-08-05 12:23:30,856 views 8120 12488 Index page accessed
INFO 2023-08-05 12:23:30,856 basehttp 8120 12488 "GET / HTTP/1.1" 200 13
INFO 2023-08-09 19:56:13,573 autoreload 9636 704 Watching for file changes with StatReloader
INFO 2023-08-09 19:56:16,739 views 9636 9440 Index page accessed
INFO 2023-08-09 19:56:16,741 basehttp 9636 9440 "GET / HTTP/1.1" 200 13
WARNING 2023-08-09 19:56:17,095 log 9636 9440 Not Found: /favicon.ico
WARNING 2023-08-09 19:56:17,096 basehttp 9636 9440 "GET /favicon.ico HTTP/1.1" 404 2545
WARNING 2023-08-09 19:56:21,812 log 9636 9440 Not Found: /les3
WARNING 2023-08-09 19:56:21,813 basehttp 9636 9440 "GET /les3 HTTP/1.1" 404 2764
WARNING 2023-08-09 19:56:30,672 log 9636 9440 Not Found: /les3/hello
WARNING 2023-08-09 19:56:30,673 basehttp 9636 9440 "GET /les3/hello HTTP/1.1" 404 2782
WARNING 2023-08-09 19:57:45,012 log 9636 9440 Not Found: /les3/hello2
WARNING 2023-08-09 19:57:45,013 basehttp 9636 9440 "GET /les3/hello2 HTTP/1.1" 404 2785
WARNING 2023-08-09 19:57:52,436 log 9636 9440 Not Found: /les3/
WARNING 2023-08-09 19:57:52,437 basehttp 9636 9440 "GET /les3/ HTTP/1.1" 404 2767
INFO 2023-08-09 19:59:59,895 autoreload 5684 6548 Watching for file changes with StatReloader
INFO 2023-08-09 20:00:01,607 views 5684 14176 Index page accessed
INFO 2023-08-09 20:00:01,609 basehttp 5684 14176 "GET / HTTP/1.1" 200 13
WARNING 2023-08-09 20:00:08,328 log 5684 14176 Not Found: /les3
WARNING 2023-08-09 20:00:08,329 basehttp 5684 14176 "GET /les3 HTTP/1.1" 404 2764
WARNING 2023-08-09 20:00:15,597 log 5684 14176 Not Found: /les3/hello/
WARNING 2023-08-09 20:00:15,598 basehttp 5684 14176 "GET /les3/hello/ HTTP/1.1" 404 2785
WARNING 2023-08-09 20:00:20,769 log 5684 14176 Not Found: /les3/hello2/
WARNING 2023-08-09 20:00:20,770 basehttp 5684 14176 "GET /les3/hello2/ HTTP/1.1" 404 2788
WARNING 2023-08-09 20:01:18,023 log 5684 14176 Not Found: /les3/hello
WARNING 2023-08-09 20:01:18,024 basehttp 5684 14176 "GET /les3/hello HTTP/1.1" 404 2782
INFO 2023-08-09 20:03:45,967 autoreload 7024 12816 Watching for file changes with StatReloader
INFO 2023-08-09 20:04:00,884 autoreload 7024 12816 C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\urls.py changed, reloading.
INFO 2023-08-09 20:04:01,358 autoreload 3924 656 Watching for file changes with StatReloader
INFO 2023-08-09 20:04:31,633 views 3924 13796 Index page accessed
INFO 2023-08-09 20:04:31,635 basehttp 3924 13796 "GET / HTTP/1.1" 200 13
INFO 2023-08-09 20:04:37,119 basehttp 3924 13796 "GET /about HTTP/1.1" 301 0
ERROR 2023-08-09 20:04:37,128 views 3924 13852 Error in about page: division by zero
Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp\views.py", line 17, in about
    result = 1 / 0
ZeroDivisionError: division by zero
INFO 2023-08-09 20:04:37,134 basehttp 3924 13852 "GET /about/ HTTP/1.1" 200 27
INFO 2023-08-09 20:05:06,346 autoreload 3924 656 C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\lesson_01\urls.py changed, reloading.
INFO 2023-08-09 20:05:06,879 autoreload 13240 3816 Watching for file changes with StatReloader
INFO 2023-08-09 20:05:07,981 views 13240 10072 Index page accessed
INFO 2023-08-09 20:05:07,983 basehttp 13240 10072 "GET / HTTP/1.1" 200 13
INFO 2023-08-09 20:05:15,347 basehttp 13240 10072 "GET /les3/hello HTTP/1.1" 301 0
INFO 2023-08-09 20:05:15,356 basehttp 13240 13108 "GET /les3/hello/ HTTP/1.1" 200 26
INFO 2023-08-09 20:07:23,226 autoreload 13240 3816 C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\urls.py changed, reloading.
INFO 2023-08-09 20:07:23,736 autoreload 6920 8188 Watching for file changes with StatReloader
INFO 2023-08-09 20:07:39,565 autoreload 6920 8188 C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\urls.py changed, reloading.
INFO 2023-08-09 20:07:40,046 autoreload 10664 13500 Watching for file changes with StatReloader
INFO 2023-08-09 20:08:24,787 autoreload 10664 13500 C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\urls.py changed, reloading.
INFO 2023-08-09 20:08:25,262 autoreload 7840 8064 Watching for file changes with StatReloader
INFO 2023-08-15 21:00:38,667 autoreload 3568 8836 Watching for file changes with StatReloader
INFO 2023-08-15 21:02:19,511 autoreload 3568 8836 C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\views.py changed, reloading.
INFO 2023-08-15 21:02:20,078 autoreload 2456 6960 Watching for file changes with StatReloader
INFO 2023-08-15 21:02:33,996 autoreload 2456 6960 C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\views.py changed, reloading.
INFO 2023-08-15 21:02:34,584 autoreload 3188 14960 Watching for file changes with StatReloader
INFO 2023-08-15 21:02:36,229 views 3188 11976 Index page accessed
INFO 2023-08-15 21:02:36,230 basehttp 3188 11976 "GET / HTTP/1.1" 200 13
WARNING 2023-08-15 21:02:36,625 log 3188 11976 Not Found: /favicon.ico
WARNING 2023-08-15 21:02:36,626 basehttp 3188 11976 "GET /favicon.ico HTTP/1.1" 404 2546
WARNING 2023-08-15 21:02:45,219 log 3188 11976 Not Found: /les3/posts
WARNING 2023-08-15 21:02:45,220 basehttp 3188 11976 "GET /les3/posts HTTP/1.1" 404 3420
INFO 2023-08-15 21:03:00,498 basehttp 3188 11976 "GET /les3/posts/2022 HTTP/1.1" 301 0
INFO 2023-08-15 21:03:00,505 basehttp 3188 10908 "GET /les3/posts/2022/ HTTP/1.1" 200 19
INFO 2023-08-15 21:03:03,764 basehttp 3188 10908 "GET /les3/posts/2022/6 HTTP/1.1" 301 0
INFO 2023-08-15 21:03:03,772 basehttp 3188 6964 "GET /les3/posts/2022/6/ HTTP/1.1" 200 21
INFO 2023-08-15 21:05:28,564 autoreload 14528 9112 Watching for file changes with StatReloader
INFO 2023-08-15 21:05:29,738 views 14528 2976 Index page accessed
INFO 2023-08-15 21:05:29,740 basehttp 14528 2976 "GET / HTTP/1.1" 200 13
INFO 2023-08-15 21:05:38,164 basehttp 14528 2976 "GET /les3/posts/2022/6/python HTTP/1.1" 301 0
INFO 2023-08-15 21:05:38,174 basehttp 14528 12780 "GET /les3/posts/2022/6/python/ HTTP/1.1" 200 360
INFO 2023-08-15 21:14:07,890 autoreload 920 14512 Watching for file changes with StatReloader
INFO 2023-08-15 21:14:09,107 views 920 12024 Index page accessed
INFO 2023-08-15 21:14:09,109 basehttp 920 12024 "GET / HTTP/1.1" 200 13
INFO 2023-08-15 21:14:12,966 basehttp 920 12024 "GET /les3 HTTP/1.1" 301 0
INFO 2023-08-15 21:14:12,989 basehttp 920 4412 "GET /les3/ HTTP/1.1" 200 176
INFO 2023-08-15 21:23:15,266 autoreload 5576 4224 Watching for file changes with StatReloader
INFO 2023-08-15 21:23:16,831 views 5576 3560 Index page accessed
INFO 2023-08-15 21:23:16,833 basehttp 5576 3560 "GET / HTTP/1.1" 200 13
WARNING 2023-08-15 21:23:30,852 log 5576 3560 Not Found: /les3/if
WARNING 2023-08-15 21:23:30,853 basehttp 5576 3560 "GET /les3/if HTTP/1.1" 404 3577
INFO 2023-08-15 21:24:08,145 autoreload 5576 4224 C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\urls.py changed, reloading.
INFO 2023-08-15 21:24:08,670 autoreload 5780 2824 Watching for file changes with StatReloader
INFO 2023-08-15 21:24:09,859 views 5780 3412 Index page accessed
INFO 2023-08-15 21:24:09,861 basehttp 5780 3412 "GET / HTTP/1.1" 200 13
INFO 2023-08-15 21:24:16,428 basehttp 5780 3412 "GET /les3/if HTTP/1.1" 301 0
INFO 2023-08-15 21:24:16,455 basehttp 5780 920 "GET /les3/if/ HTTP/1.1" 200 349
INFO 2023-08-15 21:44:00,385 autoreload 13792 4624 Watching for file changes with StatReloader
INFO 2023-08-15 21:44:01,764 views 13792 11992 Index page accessed
INFO 2023-08-15 21:44:01,766 basehttp 13792 11992 "GET / HTTP/1.1" 200 13
INFO 2023-08-15 21:44:08,182 basehttp 13792 11992 "GET /les3/index HTTP/1.1" 301 0
INFO 2023-08-15 21:44:08,192 basehttp 13792 1888 "GET /les3/index/ HTTP/1.1" 200 214
INFO 2023-08-15 21:44:13,521 basehttp 13792 1888 "GET /les3/about HTTP/1.1" 301 0
INFO 2023-08-15 21:44:13,527 basehttp 13792 14932 "GET /les3/about/ HTTP/1.1" 200 220
INFO 2023-08-16 19:01:37,083 autoreload 3516 8324 Watching for file changes with StatReloader
INFO 2023-08-16 19:01:38,648 views 3516 15316 Index page accessed
INFO 2023-08-16 19:01:38,651 basehttp 3516 15316 "GET / HTTP/1.1" 200 13
INFO 2023-08-16 19:01:45,133 basehttp 3516 15316 "GET /les3/ HTTP/1.1" 200 176
INFO 2023-08-16 19:01:49,320 basehttp 3516 15316 "GET /les3/index HTTP/1.1" 301 0
ERROR 2023-08-16 19:01:49,436 log 3516 16056 Internal Server Error: /les3/index/
Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\views.py", line 73, in index
    return render(request, "myapp3/index.html")
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-08-16 19:01:49,441 basehttp 3516 16056 "GET /les3/index/ HTTP/1.1" 500 130393
INFO 2023-08-16 19:03:33,537 views 3516 16056 Index page accessed
INFO 2023-08-16 19:03:33,539 basehttp 3516 16056 "GET / HTTP/1.1" 200 13
WARNING 2023-08-16 19:03:37,004 log 3516 16056 Not Found: /index
WARNING 2023-08-16 19:03:37,005 basehttp 3516 16056 "GET /index HTTP/1.1" 404 2528
ERROR 2023-08-16 19:03:44,545 log 3516 16056 Internal Server Error: /les3/index/
Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\views.py", line 73, in index
    return render(request, "myapp3/index.html")
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-08-16 19:03:44,548 basehttp 3516 16056 "GET /les3/index/ HTTP/1.1" 500 130393
INFO 2023-08-16 19:05:08,953 autoreload 3516 8324 C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\views.py changed, reloading.
INFO 2023-08-16 19:05:09,464 autoreload 16140 16012 Watching for file changes with StatReloader
INFO 2023-08-16 19:05:10,565 views 16140 10052 Index page accessed
INFO 2023-08-16 19:05:10,568 basehttp 16140 10052 "GET / HTTP/1.1" 200 13
ERROR 2023-08-16 19:05:14,952 log 16140 10052 Internal Server Error: /les3/index/
Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\views.py", line 73, in index
    return render(request, "index.html")
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2023-08-16 19:05:14,954 basehttp 16140 10052 "GET /les3/index/ HTTP/1.1" 500 81965
INFO 2023-08-16 19:05:36,189 autoreload 16140 16012 C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\views.py changed, reloading.
INFO 2023-08-16 19:05:36,917 autoreload 980 13192 Watching for file changes with StatReloader
INFO 2023-08-16 19:05:38,711 views 980 8076 Index page accessed
INFO 2023-08-16 19:05:38,713 basehttp 980 8076 "GET / HTTP/1.1" 200 13
ERROR 2023-08-16 19:05:44,827 log 980 8076 Internal Server Error: /les3/index/
Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\views.py", line 73, in index
    return render(request, "myapp3/index.html")
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-08-16 19:05:44,830 basehttp 980 8076 "GET /les3/index/ HTTP/1.1" 500 130393
INFO 2023-08-16 19:06:14,008 basehttp 980 8076 "GET /les3/about HTTP/1.1" 301 0
INFO 2023-08-16 19:06:14,027 basehttp 980 4012 "GET /les3/about/ HTTP/1.1" 200 220
INFO 2023-08-16 19:07:10,386 autoreload 9616 3860 Watching for file changes with StatReloader
INFO 2023-08-16 19:07:12,096 views 9616 15952 Index page accessed
INFO 2023-08-16 19:07:12,098 basehttp 9616 15952 "GET / HTTP/1.1" 200 13
ERROR 2023-08-16 19:07:17,289 log 9616 15952 Internal Server Error: /les3/index/
Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\views.py", line 73, in index
    return render(request, "myapp3/index.html")
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-08-16 19:07:17,295 basehttp 9616 15952 "GET /les3/index/ HTTP/1.1" 500 130393
INFO 2023-08-16 19:12:06,370 autoreload 13640 14236 Watching for file changes with StatReloader
ERROR 2023-08-16 19:12:08,086 log 13640 2704 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\views.py", line 73, in index
    return render(request, "myapp3/index.html")
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-08-16 19:12:08,099 basehttp 13640 2704 "GET / HTTP/1.1" 500 130239
INFO 2023-08-16 19:14:37,307 autoreload 4368 2732 Watching for file changes with StatReloader
ERROR 2023-08-16 19:14:39,135 log 4368 9432 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\views.py", line 73, in index
    return render(request, "myapp3/index.html")
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-08-16 19:14:39,138 basehttp 4368 9432 "GET / HTTP/1.1" 500 130239
INFO 2023-08-16 19:15:49,073 autoreload 11900 14756 Watching for file changes with StatReloader
INFO 2023-08-16 19:15:50,367 basehttp 11900 9204 "GET / HTTP/1.1" 200 302
INFO 2023-08-16 19:18:22,069 autoreload 11900 14756 C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\models.py changed, reloading.
INFO 2023-08-16 19:18:22,759 autoreload 5316 12280 Watching for file changes with StatReloader
INFO 2023-08-16 19:49:21,023 autoreload 15788 2848 Watching for file changes with StatReloader
INFO 2023-08-16 19:49:23,694 basehttp 15788 6308 "GET / HTTP/1.1" 200 302
INFO 2023-08-16 19:49:34,477 basehttp 15788 6308 "GET /les3/author/5 HTTP/1.1" 301 0
INFO 2023-08-16 19:49:34,494 basehttp 15788 15912 "GET /les3/author/5/ HTTP/1.1" 200 1188
ERROR 2023-08-16 19:49:37,708 log 15788 15912 Internal Server Error: /les3/post/35/
Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\views.py", line 90, in post_full
    return render(request, 'myapp3/post_full.html', {'post': post})
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp3/post_full.html
ERROR 2023-08-16 19:49:37,711 basehttp 15788 15912 "GET /les3/post/35/ HTTP/1.1" 500 82301
INFO 2023-08-16 19:50:39,025 basehttp 15788 15912 "GET /les3/author/5/ HTTP/1.1" 200 1188
ERROR 2023-08-16 19:50:41,203 log 15788 15912 Internal Server Error: /les3/post/31/
Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\views.py", line 90, in post_full
    return render(request, 'myapp3/post_full.html', {'post': post})
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp3/post_full.html
ERROR 2023-08-16 19:50:41,205 basehttp 15788 15912 "GET /les3/post/31/ HTTP/1.1" 500 82301
ERROR 2023-08-16 19:52:39,915 log 15788 15912 Internal Server Error: /les3/post/34/
Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\views.py", line 90, in post_full
    return render(request, 'myapp3/post_full.html', {'post': post})
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp3/post_full.html
ERROR 2023-08-16 19:52:39,916 basehttp 15788 15912 "GET /les3/post/34/ HTTP/1.1" 500 82301
INFO 2023-08-16 19:52:43,480 basehttp 15788 15912 "GET /les3/post/1 HTTP/1.1" 301 0
ERROR 2023-08-16 19:52:43,516 log 15788 8588 Internal Server Error: /les3/post/1/
Traceback (most recent call last):
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\lesson_01\myapp3\views.py", line 90, in post_full
    return render(request, 'myapp3/post_full.html', {'post': post})
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Admin\MyProjectsPython\GB_Django\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp3/post_full.html
ERROR 2023-08-16 19:52:43,518 basehttp 15788 8588 "GET /les3/post/1/ HTTP/1.1" 500 82122
INFO 2023-08-16 19:53:56,579 autoreload 10840 15820 Watching for file changes with StatReloader
INFO 2023-08-16 19:53:57,565 basehttp 10840 13032 "GET / HTTP/1.1" 200 302
INFO 2023-08-16 19:54:01,413 basehttp 10840 13032 "GET /les3/author/5/ HTTP/1.1" 200 1188
INFO 2023-08-16 19:54:03,458 basehttp 10840 13032 "GET /les3/post/35/ HTTP/1.1" 200 673
